name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - someaddons
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug you're experiencing
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproducability
      description: Which steps are needed to reproduce this bug?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Mod up to date
      description:
      options:
        - label: Before submitting this issue I updated to the newest version and reproduced it
          required: true
  - type: dropdown
    id: version
    attributes:
      label: Minecraft version
      description: What version of our Minecraft are you running?
      options:
        - 1.16.5
        - 1.18.1
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Modloader version
      description: Which modloader are you using? Only Forge/Fabric is supported.
      options:
        - Forge
        - Fabric
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Logs
      description: Please upload your log file from logs/latest.log to https://gist.github.com/ and put in the link below. No matter if you think it is relevant or not.
      placeholder: ex. https://gist.github.com/someaddons/aa5986b9495863c3b5
    validations:
      required: true
